name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python-version }}
      - name: Tests v0_1
        if: always()
        run: python -m unittest discover -s tests -p "test_v0_1.py"
        env:
          PYTHONPATH: src
      - name: Tests v0_2
        if: always()
        run: python -m unittest discover -s tests -p "test_v0_2.py"
        env:
          PYTHONPATH: src
      - name: Tests v0_3
        if: always()
        run: python -m unittest discover -s tests -p "test_v0_3.py"
        env:
          PYTHONPATH: src
      - name: Tests v0_4
        if: always()
        run: python -m unittest discover -s tests -p "test_v0_4.py"
        env:
          PYTHONPATH: src
      - name: Tests v1_0
        if: always()
        run: python -m unittest discover -s tests -p "test_v1_0.py"
        env:
          PYTHONPATH: src
